### ISSUE TITLE
When opening the page of an app, should fetch useful info using Marketplace API and display it on the page

### ISSUE THREAD

**Issue by asdofindia** [asdofindia/mozkapps#1]
While opening the dedicated page of an app, like https://asdofindia.github.io/mozkapps/flasher/ a call should be made to marketplace [api for app info](https://firefox-marketplace-api.readthedocs.org/en/latest/topics/apps.html#get--api-v2-apps-app-%28int-id%29|%28string-slug%29-) and relevant info should be displayed.

The XHR and rendering code should be added to js/app.js
The elements [#author, #size](https://github.com/asdofindia/mozkapps/blob/gh-pages/_layouts/app.html), etc can be used to render the info

**Comment by jigs1212** [comment]
Let Me try doing it :+1:
